name: plexos2pras
dependencies:
  - python=3
  - h5py
  - numpy
  - pandas
  - openpyxl
  - xlrd
  - cython
  - pip:
    - https://github.nrel.gov/PCM/h5plexos/archive/master.zip
    - https://github.nrel.gov/ResourceAdequacySuite/PLEXOS2PRAS/archive/master.zip
