name: plexos2pras
channels:
  - conda-forge
dependencies:
  - python=3
  - h5py
  - numpy
  - pandas
  - openpyxl
  - xlrd
  - cython
  - julia
  - pip:
    - https://github.nrel.gov/PCM/h5plexos/archive/master.zip
    - https://github.nrel.gov/ResourceAdequacySuite/PLEXOS2PRAS/archive/v0.2.0.zip
